### ISSUE TITLE
Allow compounds not available in the wwPDB components dictionary

### ISSUE THREAD

**Issue by bienchen** [ihmwg/python-modelcif#21]
Hello,

in [ModelArchive (MA)](https://modelarchive.org/) we may see novel compounds/ ligands in the future. Those compounds are not necessarily stored in the [chemical components dictionary (CCD) of wwPDB](https://www.wwpdb.org/data/ccd). Some of them may be so artificial that they can not be considered to be stored in the _wwPDB CCD_. To still make novel compounds available in MA, two approaches should be established: Let MA have its own CCD and let ModelCIF file define their own compounds locally, if needed.

That means in the future we should have three kinds of sources for chemical components in ModelCIF files: _wwPDB CCD_, _MA CCD_, _locally defined_. This is facilitated by a new item to the [`_chem_comp`](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/chem_comp.html) category - [`_chem_comp.ma_provenance`](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_chem_comp.ma_provenance.html).

In case, `ma_provenance` is "[CCD local](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_chem_comp.ma_provenance.html)", a new data category must be populated with data - [`ma_chem_comp_descriptor`](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Categories/ma_chem_comp_descriptor.html), linked back to `_chem_comp` via [`_ma_chem_comp_descriptor.chem_comp_id`](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_chem_comp_descriptor.chem_comp_id.html).

Having that scheme to introduce own compounds to ModelCIF files is a feature we need available for ModelArchive.

After looking into the code a bit, I think maybe having classes inheriting from [`ihm.ChemComp`](https://python-ihm.readthedocs.io/en/latest/main.html?highlight=chemcomp#ihm.ChemComp) available for `ma_provenance` "CCD local" and "CCD MA" would be an idea. Then for the ModelCIF file `_chem_comp.ma_provenance` could be set depending on the class of the compound or the availability of a certain attribute.
Adding `_ma_chem_comp_descriptor` seems to be not complicated, but is there a way that having a "CCD local" compound enforces having `_ma_chem_comp_descriptor`?

Thanks,

B

**Comment by benmwebb** [comment]
We do something similar in python-ihm for cross-linkers, which are often not in CCD either - the [ihm.ChemDescriptor](https://python-ihm.readthedocs.io/en/latest/main.html#ihm.ChemDescriptor) class. I think inheriting from `ihm.ChemComp` is potentially problematic as the `ChemComp` class hierarchy is already used to distinguish DNA/RNA/L-peptide/D-peptide/water/non-polymer. So you'd have to add a mixin class or assume that such custom components are always a single type, e.g. non-polymers.

A solution that avoids that problem would be to just have `ChemComp` take an extra `descriptors` argument, a list of `Descriptor` objects. python-ihm wouldn't define any (since the dictionary doesn't support that) but python-modelcif could. Then you'd just write out `chem_comp.ma_provenance "CCD local"` if `descriptors` is non-empty. (This would also allow multiple descriptors, e.g. inchi plus smiles.) Something like

```
class ChemComp(object):
    def __init__(self, id, code, code_canonical, name=None, formula=None, descriptors=None):
...
class Descriptor(object):
    pass

class InChIKeyDescriptor(Descriptor):
    type = "InChI Key"
    def __init__(self, value, details=None, software=None):
         ...

delamanid = ihm.NonPolymerChemComp(
    id=..., name="Delamanid",
    descriptors=[modelcif.InChIKeyDescriptor(value="XDAOLTSRNUSPPH-XMMPIXPASA-N")])
```

**Comment by bienchen** [comment]
Looks like a good idea to me. Simply keep all the unknown ligand's info nicely together. If we manage to find out what to do about PDB format `CONECT` records, I guess they could be handled in a similar way.

**Comment by bienchen** [comment]
I tested the new feature and it works as expected. Compounds get marked as "local" and get annotated their list of descriptors. Thanks a lot.
